# -*- coding: utf-8 -*-
"""Visualización de Datos.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ibL9WO53JjucVKMy7K1bdHdh9xQ-Fcr4
"""

#app_streamlit.py
"""
Panel de Control Universitario
Análisis de Admisiones, Retención y Satisfacción Estudiantil
Basado en university_student_data.csv
"""

#Configuración de la página
st.set_page_config(page_title="Panel Universitario", layout="wide")
st.title("🎓 Panel de Control Universitario")
st.caption("Explora indicadores de admisión, matrícula, retención y satisfacción estudiantil.")

#Cargar los datos
@st.cache_data
def cargar_datos(ruta="university_student_data.csv"):
    datos = pd.read_csv(ruta)
    datos.columns = [columna.strip() for columna in datos.columns]
    return datos

try:
    df = cargar_datos()
except Exception as e:
    st.error(f"No se pudo cargar el archivo CSV: {e}")
    st.stop()

#Definición de columnas principales
COL_ANIO = "Year"
COL_TERMINO = "Term"
COL_SOLICITUDES = "Applications"
COL_ADMITIDOS = "Admitted"
COL_MATRICULADOS = "Enrolled"
COL_RETENCION = "Retention Rate (%)"
COL_SATISFACCION = "Student Satisfaction (%)"
FACULTADES = [c for c in df.columns if c.endswith("Enrolled")]

#Barra lateral de filtros
st.sidebar.header("Filtros disponibles")
anios = sorted(df[COL_ANIO].dropna().unique().tolist())
terminos = sorted(df[COL_TERMINO].dropna().unique().tolist())

anios_seleccionados = st.sidebar.multiselect("Seleccionar año(s)", options=anios, default=[anios[-1]])
terminos_seleccionados = st.sidebar.multiselect("Seleccionar término(s)", options=terminos, default=terminos)

#Aplicar los filtros seleccionados
df_filtrado = df.copy()
if anios_seleccionados:
    df_filtrado = df_filtrado[df_filtrado[COL_ANIO].isin(anios_seleccionados)]
if terminos_seleccionados:
    df_filtrado = df_filtrado[df_filtrado[COL_TERMINO].isin(terminos_seleccionados)]

#Indicadores principales (KPIs)
st.header("📊 Indicadores clave")
col1, col2, col3 = st.columns(3)

total_solicitudes = int(df_filtrado[COL_SOLICITUDES].sum())
total_matriculados = int(df_filtrado[COL_MATRICULADOS].sum())
promedio_retencion = df_filtrado[COL_RETENCION].mean()

col1.metric("Solicitudes totales", f"{total_solicitudes:,}")
col2.metric("Matriculados totales", f"{total_matriculados:,}")
col3.metric("Retención promedio", f"{promedio_retencion:.2f}%")

st.markdown("---")

#Pestañas de visualización
pestana1, pestana2, pestana3 = st.tabs(["📈 Series temporales", "🏫 Facultades", "📋 Tabla de datos"])

#Pestaña 1: Series
with pestana1:
    st.subheader("Evolución de solicitudes por año y término")
    grafico_solicitudes = px.line(
        df_filtrado.sort_values(COL_ANIO),
        x=COL_ANIO,
        y=COL_SOLICITUDES,
        color=COL_TERMINO,
        markers=True,
        title="Tendencia de solicitudes de admisión"
    )
    st.plotly_chart(grafico_solicitudes, use_container_width=True)

    st.subheader("Promedio de tasa de retención por año")
    df_retencion = df_filtrado.groupby(COL_ANIO, as_index=False)[COL_RETENCION].mean()
    grafico_retencion = px.line(
        df_retencion,
        x=COL_ANIO,
        y=COL_RETENCION,
        markers=True,
        title="Tasa de retención promedio por año"
    )
    st.plotly_chart(grafico_retencion, use_container_width=True)

#Pestaña 2: Facultades
with pestana2:
    st.subheader("Distribución de matriculados por facultad")
    if FACULTADES:
        df_facultades = df_filtrado.groupby(COL_ANIO, as_index=False)[FACULTADES].sum()
        grafico_facultades = px.area(
            df_facultades,
            x=COL_ANIO,
            y=FACULTADES,
            title="Evolución de matriculados por facultad"
        )
        st.plotly_chart(grafico_facultades, use_container_width=True)
    else:
        st.warning("No se encontraron columnas de facultades.")

    st.subheader("Relación entre satisfacción y retención")
    grafico_dispersion = px.scatter(
        df_filtrado,
        x=COL_SATISFACCION,
        y=COL_RETENCION,
        color=COL_ANIO,
        size=COL_SOLICITUDES,
        title="Satisfacción estudiantil vs Tasa de retención"
    )
    st.plotly_chart(grafico_dispersion, use_container_width=True)

    correlacion = df_filtrado[[COL_SATISFACCION, COL_RETENCION]].corr().iloc[0, 1]
    st.write(f"📈 Correlación entre satisfacción y retención: **{correlacion:.3f}**")

#Pestaña 3: Tabla y descarga
with pestana3:
    st.subheader("Datos filtrados")
    st.dataframe(df_filtrado.reset_index(drop=True), use_container_width=True)

    #Descargar CSV filtrado
    csv = df_filtrado.to_csv(index=False).encode("utf-8")
    b64 = base64.b64encode(csv).decode()
    enlace_descarga = f'<a href="data:file/csv;base64,{b64}" download="datos_filtrados.csv">📥 Descargar datos filtrados</a>'
    st.markdown(enlace_descarga, unsafe_allow_html=True)

st.markdown("---")
st.caption("Panel desarrollado en Streamlit — Datos institucionales de admisión, retención y satisfacción estudiantil.")